declare module "quill/formats/bold";
declare module "quill/formats/header";
declare module "quill/formats/italic";
declare module "quill/formats/link";
declare module "quill/formats/list";
declare module "quill/formats/underline";
declare module "quill/modules/toolbar";
declare module "quill/themes/snow";
declare module "quill/ui/icons";
